name: test_flutter_alarm
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  alarm: ^4.0.7
  permission_handler: ^11.3.1
  intl: ^0.19.0
  http: ^1.2.2
  freezed_annotation: ^2.4.4
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  isar: ^3.1.0+1
  isar_generator: ^3.1.0+1
  path_provider: ^2.1.1
  isar_flutter_libs: ^3.1.0+1
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8
  bubble: ^1.2.1
  fl_chart: ^0.69.0
  drag_and_drop_lists: ^0.4.1
  flutter_colorpicker: ^1.0.3

  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  scroll_to_index: ^3.0.1
  external_path: ^2.0.1
  charset_converter: ^2.2.0
  scrollable_positioned_list: ^0.3.8
  share_plus: ^10.0.0
  file_picker: ^8.0.5
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1

flutter:

  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: KiwiMaru
      fonts:
        - asset: assets/fonts/KiwiMaru-Light.ttf
        - asset: assets/fonts/KiwiMaru-Medium.ttf
        - asset: assets/fonts/KiwiMaru-Regular.ttf

flutter_native_splash:
  image: "assets/images/alarmbird.png"
  color: "212121"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"
